export const CREATE_USER_REQUESTED = "CREATE_USER_REQUESTED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const LOGIN_ACCESS_REQUESTED = "LOGIN_ACCESS_REQUESTED";
export const LOGIN_ACCESS_SUCCESS = "LOGIN_ACCESS_SUCCESS";
export const LOGIN_ACCESS_FAIL = "LOGIN_ACCESS_FAIL";

export const RESET_DATA = "RESET_DATA";